In [1]:
#Importing os

In [2]:
import os

In [3]:
#Importing Imortent Libaries

In [4]:
import pandas as pd
import numpy as np
import os
import glob
import tensorflow as tf

In [5]:
#Importing libaries for Image

In [6]:
import PIL
from PIL import Image
import imageio

In [7]:
#For data visualization

In [8]:
import matplotlib.pyplot as plt
import seaborn as sn
import numpy as np
import pathlib

In [9]:
#For geeting the current Directory

In [10]:
os.getcwd()

'D:\\Jupyter Notebook\\Brain_Tumor Project'

In [11]:
import os
for dirname, _, filename in os.walk('D:\\BrainTumor\\archive\\'):
    for filename in filenames:
        print(os.path.joint(dirname,filename))

In [12]:
import cv2
import matplotlib.pyplot as plt
import os
import tensorflow as tf
from tensorflow import keras
from PIL import Image
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import normalize
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D
from keras.layers import Activation, Dropout,Flatten,Dense
from tensorflow.keras.utils import to_categorical

In [13]:
#Geting path of the file 

In [14]:
image_directory=('D:\\Brain_Tumer\\archive\\')

In [15]:
no_tumer_images=os.listdir('D:\\Jupyter Notebook\\Brain_Tumor Project\\archive\\no')

In [16]:
yes_tumer_images=os.listdir('D:\\Jupyter Notebook\\Brain_Tumor Project\\archive\\yes')

In [17]:
#Initialize dataset and label arrays

In [18]:
dataset=[]
label=[]

In [19]:
#Loop over each image in each catagort
#For image labelled with no

In [20]:
for i,image_name in enumerate(no_tumer_images):
    if(image_name.split('.')[1]=='jpg'):
        image=cv2.imread('D:/Jupyter Notebook/Brain_Tumor Project/archive/no/'+image_name)
        image=Image.fromarray(image,'RGB')
        image=image.resize((64,64))
        dataset.append(np.array(image))
        label.append(0)

In [21]:
#Loop over each image in each catagort
#For image labelled with yes

In [22]:
for i,image_name in enumerate(yes_tumer_images):
    if(image_name.split('.')[1]=='jpg'):
        image=cv2.imread('D:/Jupyter Notebook/Brain_Tumor Project/archive/yes/'+image_name)
        image=Image.fromarray(image,'RGB')
        image=image.resize((64,64))
        dataset.append(np.array(image))
        label.append(1)

In [23]:
dataset=np.array(dataset)
label=np.array(label)

In [24]:
print("###########DATA_SET###########")
print(dataset)

###########DATA_SET###########
[[[[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  [[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  [[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  ...

  [[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  [[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  [[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]]


 [[[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  [[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  [[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  ...

  [[ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]
   ...
   [ 0  0  0]
   [ 0  0  0]
   [ 0  0  0]]

  [[ 0  0  0]
   [ 0  0

In [25]:
print("###########LABEL###########")
print(label)

###########LABEL###########
[0 0 0 ... 1 1 1]


In [26]:
print(len(label))

3000


In [27]:
#convert the dataset and Label to numy array 

In [28]:
dataset=np.array(dataset)
label=np.array(label)
print("##########")

##########


In [29]:
x_train, x_test, y_train, y_test = train_test_split(dataset, label, test_size = 0.2, random_state = 42)

In [30]:
print(x_train.shape)
print(y_train.shape)

(2400, 64, 64, 3)
(2400,)


In [31]:
print(x_test.shape)
print(y_test.shape)

(600, 64, 64, 3)
(600,)


In [32]:
#Notmalise the data for training purpose

In [33]:
x_train=normalize(x_train,axis=1)
x_test=normalize(x_test,axis=1)
print("#################")

#################


In [34]:
#Creating CNN Model

In [35]:
model=Sequential()

In [36]:
model.add(Conv2D(32, (3,3), input_shape = (64,64, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

In [37]:
model.add(Conv2D(32, (3,3), kernel_initializer = 'he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

In [38]:
model.add(Conv2D(64, (3,3),  kernel_initializer = 'he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

In [39]:
model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))

In [40]:
model.add(Activation('sigmoid'))

In [41]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 62, 62, 32)        896       
                                                                 
 activation (Activation)     (None, 62, 62, 32)        0         
                                                                 
 max_pooling2d (MaxPooling2D  (None, 31, 31, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 29, 29, 32)        9248      
                                                                 
 activation_1 (Activation)   (None, 29, 29, 32)        0         
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 14, 14, 32)       0         
 2D)                                                    

In [42]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [43]:
model.fit(x_train,y_train,
         batch_size=16,
         verbose=1,
         epochs=10,
         validation_data=(x_test,y_test),
        shuffle='False')

Epoch 1/10
150/150 [==============================] - 8s 48ms/step - loss: 0.5505 - accuracy: 0.7138 - val_loss: 0.4172 - val_accuracy: 0.8083
Epoch 2/10
150/150 [==============================] - 7s 49ms/step - loss: 0.4170 - accuracy: 0.8213 - val_loss: 0.3205 - val_accuracy: 0.8583
Epoch 3/10
150/150 [==============================] - 8s 51ms/step - loss: 0.3258 - accuracy: 0.8646 - val_loss: 0.2576 - val_accuracy: 0.8900
Epoch 4/10
150/150 [==============================] - 8s 53ms/step - loss: 0.2494 - accuracy: 0.9079 - val_loss: 0.2082 - val_accuracy: 0.9200
Epoch 5/10
150/150 [==============================] - 8s 51ms/step - loss: 0.1833 - accuracy: 0.9358 - val_loss: 0.1495 - val_accuracy: 0.9550
Epoch 6/10
150/150 [==============================] - 8s 51ms/step - loss: 0.1184 - accuracy: 0.9613 - val_loss: 0.1455 - val_accuracy: 0.9483
Epoch 7/10
150/150 [==============================] - 8s 53ms/step - loss: 0.0776 - accuracy: 0.9754 - val_loss: 0.1055 - val_accuracy: 0.9750

In [44]:
model.save('Brain_Tumor_detection.h5')

In [45]:
import cv2
from keras.models import load_model
from PIL import Image
import numpy as np

In [46]:
model=load_model('Brain_Tumor_detection.h5')

In [47]:
#Testing on Image

In [53]:
image=cv2.imread('D:\\Jupyter Notebook\\Brain_Tumor Project\\archive\\pred\\pred13.jpg')
img=Image.fromarray(image)
img=img.resize((64,64))
img=np.array(img)
print(img)
input_img = np.expand_dims(img, axis=0)

[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 1  1  1]
  [ 4  4  4]
  [ 4  4  4]
  ...
  [ 2  2  2]
  [ 0  0  0]
  [ 0  0  0]]

 ...

 [[ 8  8  8]
  [22 22 22]
  [22 22 22]
  ...
  [11 11 11]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 8  8  8]
  [22 22 22]
  [22 22 22]
  ...
  [11 11 11]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 8  8  8]
  [22 22 22]
  [22 22 22]
  ...
  [10 10 10]
  [ 0  0  0]
  [ 0  0  0]]]


In [54]:
result=model.predict(input_img)
print(result)
print("Result Predicted")

1/1 [==============================] - 0s 31ms/step
[[1.]]
Result Predicted


In [55]:
#Testing on another image

In [56]:
image=cv2.imread('D:\\Jupyter Notebook\\Brain_Tumor Project\\archive\\pred\\pred0.jpg')
img=Image.fromarray(image)
img=img.resize((64,64))
img=np.array(img)
print(img)
input_img=np.expand_dims(img,axis=0)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [57]:
result=model.predict(input_img)
print(result)
print("Result Predicted")

1/1 [==============================] - 0s 39ms/step
[[0.]]
Result Predicted
